apiVersion: clustersecret.io/v1
kind: ClusterSecret
metadata:
  name: basic-cluster-secret
  namespace: example-1
data:
  username: MTIzNDU2Cg==
  password: MTIzNDU2Cg==
---
kind: ClusterSecret
apiVersion: clustersecret.io/v1
metadata:
  name: typed-secret
  namespace: example-1
  type: kubernetes.io/tls
data:
  tls.crt: MTIzNDU2Cg==
  tls.key: MTIzNDU2Cg==
---
apiVersion: clustersecret.io/v1
kind: ClusterSecret
metadata:
  name: basic-cluster-secret
  namespace: example-1
avoidNamespaces:
  - example-3
---