# A demo custom resource for the Kopf example operators.
apiVersion: clustersecret.io/v1
kind: cluster-secret
metadata:
  name: global-secret2
  namespace: clustersecret
matchNamespace:
  - 'cluster.*'
  # it will be replicated in clustersecret namespace.
data:
  username: YWRtaW4=
  password: MWYyZDFlMmU2N2Rm
