clustersecret:
  clustersecret:
    image:
      repository: flag5/clustersecret
      tag: 0.0.10
      # use tag__arm32 for ARM builds
      # If Clustersecret is about to create a secret and then it founds it exists:
      # Default is to ignore it. (to not loose any unintentional data)
      # It can also reeplace it. Just uncommenting next line.
      # replace_existing: 'true'
kubernetesClusterDomain: cluster.local
