apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cluster-secret.fullname" . }}-account
  labels:
  {{- include "cluster-secret.labels" . | nindent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cluster-secret.fullname" . }}-clustersecret
  labels:
    app: clustersecret
  {{- include "cluster-secret.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: clustersecret
    {{- include "cluster-secret.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: clustersecret
      {{- include "cluster-secret.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ .Values.kubernetesClusterDomain }}
        - name: CLUSTER_SECRET_VERSION
          value: {{ .Chart.AppVersion | quote }}
        - name: REPLACE_EXISTING
          value: {{ .Values.clustersecret.clustersecret.replace_existing | default "false" | quote }}
        - name: NAMESPACE
          value: {{ .Release.Namespace }}
        - name: SERVICE_NAME
          value: {{ include "cluster-secret.fullname" . }}-clustersecret-webhook
        - name: SERVICE_PORT
          value: "443"
        - name: CONTAINER_PORT
          value: "9443"
        - name: WEBHOOK_NAME
          value: "auto.kopf.dev"
        image: {{ .Values.clustersecret.clustersecret.image.repository }}:{{ .Values.clustersecret.clustersecret.image.tag
          | default .Chart.AppVersion }}
        name: clustersecret
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          periodSeconds: 120
        resources: {}
      serviceAccountName: {{ include "cluster-secret.fullname" . }}-account
